const actions = {
  DSDONTHUCANCHUYENDONVBDD_INIT: "DSDONTHUCANCHUYENDONVBDD_INIT",
  DSDONTHUCANCHUYENDONVBDD_INIT_SUCCESS: "DSDONTHUCANCHUYENDONVBDD_INIT_SUCCESS",
  DSDONTHUCANCHUYENDONVBDD_INIT_ERROR: "DSDONTHUCANCHUYENDONVBDD_INIT_ERROR",
  

  getData: (filterData) => ({
    type: actions.DSDONTHUCANCHUYENDONVBDD_INIT,
    payload: { filterData },
  }),
};

export default actions;
