const actions = {
  GET_DANHSACH_DONTHUCANPHEDUYET: "GET_DANHSACH_DONTHUCANPHEDUYET",
  GET_DANHSACH_DONTHUCANPHEDUYET_SUCCESS:
    "GET_DANHSACH_DONTHUCANPHEDUYET_SUCCESS",
  GET_DANHSACH_DONTHUCANPHEDUYET_ERROR: "GET_DANHSACH_DONTHUCANPHEDUYET_ERROR",

  getData: (filterData) => ({
    type: actions.GET_DANHSACH_DONTHUCANPHEDUYET,
    payload: { filterData },
  }),
};

export default actions;
