const actions = {
  GET_DATA_PHEDUYETKETQUAXULY: "GET_DATA_PHEDUYETKETQUAXULY",
  GET_DATA_PHEDUYETKETQUAXULY_SUCCESS: "GET_DATA_PHEDUYETKETQUAXULY_SUCCESS",
  GET_DATA_PHEDUYETKETQUAXULY_ERROR: "GET_DATA_PHEDUYETKETQUAXULY_ERROR",


  getData: (filterData) => ({
    type: actions.GET_DATA_PHEDUYETKETQUAXULY,
    payload: { filterData },
  }),
};

export default actions;
